# Generated by Django 2.1.5 on 2019-01-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveIntegerField(choices=[(0, 'Вор'), (1, 'Покупатель')], verbose_name='Категория')),
                ('face_descriptor', models.BinaryField(blank=True, null=True, verbose_name='Дескриптор лица')),
            ],
        ),
        migrations.CreateModel(
            name='PersonFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_type', models.PositiveIntegerField(blank=True, choices=[(0, 'Фас'), (1, 'Профиль'), (2, 'Вполоборота')], default=0, verbose_name='Описание фото')),
                ('foto', models.ImageField(upload_to='faces', verbose_name='Фото')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_detector.Person', verbose_name='Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='main_foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_foto', to='face_detector.PersonFoto', verbose_name='Основное фото'),
        ),
    ]
