# Generated by Django 2.1.5 on 2019-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='face_descriptor',
        ),
        migrations.RemoveField(
            model_name='personfoto',
            name='foto_type',
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='personfoto',
            name='face_descriptor',
            field=models.BinaryField(blank=True, null=True, verbose_name='Дескриптор лица'),
        ),
    ]
