# Generated by Django 2.1.5 on 2019-02-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0002_auto_20190201_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfoto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='faces', verbose_name='Фото'),
        ),
    ]
