# Generated by Django 2.1.5 on 2019-02-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0003_auto_20190204_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата фиксации')),
                ('uuid', models.UUIDField(blank=True, verbose_name='Идентификатор')),
                ('foto', models.ImageField(blank=True, upload_to='similarity', verbose_name='')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='face_detector.Person', verbose_name='Субъект')),
            ],
        ),
    ]
