# Generated by Django 2.1.5 on 2019-02-13 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0004_similarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='id',
        ),
        migrations.AlterField(
            model_name='similarity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
