# Generated by Django 2.1.5 on 2019-02-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0005_auto_20190213_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='main_foto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_foto', to='face_detector.PersonFoto', verbose_name='Основное фото'),
        ),
    ]
