# Generated by Django 2.1.5 on 2019-02-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0006_auto_20190214_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='person',
        ),
        migrations.AddField(
            model_name='similarity',
            name='person',
            field=models.ManyToManyField(to='face_detector.Person', verbose_name='Субъект'),
        ),
    ]
