# Generated by Django 2.1.5 on 2019-02-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0007_auto_20190215_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarity',
            name='is_send',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отправлена клиенту'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='foto',
            field=models.ImageField(blank=True, upload_to='similarity', verbose_name='Кадр БД+камера'),
        ),
    ]
